import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/layouts/navbar/page";
import FooterPage from "@/layouts/footer/page";
import Sidebar from "@/layouts/sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TechMinds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className={inter.className}>
  
        <div className="flex "> 
          <div className="flex-grow reletive">
            {children}
          </div>
              <div className="absolute top-0">
        <Navbar />
        </div>
          <div className="absolute right-0">
            <Sidebar />
          </div>
        </div>
        <FooterPage />
      </body>
    </html>
  );
}
